TAG: "default"
MODEL: "default"
DATA:
  TRAINSET: "Liver_2016_train+Liver_2017_train"
  VALSET: "Liver_2017_test"
  TESTSET: "Liver_2017_test"
TRAIN:
  BS: 8
  DISPLAY: 100
  KEEP_PROB: 0.7
  LR: 0.01
  LR_STEP: [500000]
  MAX_ITERS: 500000
  SNAPSHOT_ITERS: 5000
TEST:
  BS_2D: 8
  BS_3D: 1
  ITER: 500000
MODEL:
  ACTIVATION: "relu"
  WEIGHT_DECAY: 1.0
  INIT_CHANNELS: 24
  BLOCKS: 3
  NUM_LAYERS_PER_BLOCK: 12
  GROWTH_RATE: 12
  THRESHOLD: 0.5
  WEIGHT_INITIALIZER: "trunc_norm"
