TAG: "default"
MODEL: "default"
PRED_TAG: "default"
IMG:
  BIT: 16
  W_WIDTH: 250
  W_LEVEL: 55
DATA:
  TRAINSET: "Liver_2016_train+Liver_2017_train"
  VALSET: "Liver_2017_test"
  TESTSET: "Liver_2017_test"
  TESTSET_3D: "Liver_2017_test_3D"
TRAIN:
  BS: 2
  DISPLAY: 100
  KEEP_PROB: 1.0
  LR: 0.001
  LR_DECAY: 0.1
  LR_STEP: [100000]
  MAX_ITERS: 200000
  SNAPSHOT_ITERS: 5000
VAL:
  NEED: True
  NUMBER: 578
  STEPS: 3000
  MAP: "bin"
TEST:
  BS_2D: 2
  BS_3D: 1
  ITER: 115000
MODEL:
  ACTIVATION: "relu"
  BLOCKS: 4
  CROSS_ENTROPY: 1.0
  GROWTH_RATE: 16
  INIT_CHANNELS: 32
  NUM_LAYERS_PER_BLOCK: [4,6,8,12]
  THETA: 1.0
  THRESHOLD: 0.5
  WEIGHT_DECAY: 0.0001
  WEIGHT_INITIALIZER: "trunc_norm"
