TAG: "dice_skipv2"
PREFIX: "default"
PRED_TAG: ""
IMG:
  BIT: 16
  W_WIDTH: 250
  W_LEVEL: 55
DATA:
  TESTSET: "a"
TRAIN:
  BS: 10
  DISPLAY: 200
  KEEP_PROB: 1.0
  LOSS: "dice"
  LOSS_WEIGHT: 1.0
  LOSS_GAMMA: 0.0
  LR: 0.001
  LR_DECAY: 0.1
  LR_STEP: [100000,180000]
  MAP: "prob"
  MAX_ITERS: 250000
  SNAPSHOT_ITERS: 5000
  UPDATE_OPS: True
VAL:
  NEED: True
  NUMBER: 1000
  STEPS: 5000
  MAP: "bin"
TEST:
  BS_2D: 1
  BS_3D: 1
  ITER: 250000
  SAVE_MODEL: True
MODEL:
  ACTIVATION: "relu"
  BLOCKS: 4
  GROWTH_RATE: 16
  INIT_CHANNELS: 32
  NUM_LAYERS_PER_BLOCK: [4,6,8,12]
  THETA: 1.0
  THRESHOLD: 0.5
  WEIGHT_DECAY: 0.0001
  WEIGHT_INITIALIZER: "trunc_norm"
  SKIP_CONNECT: True
  SKIP_CONNECT_V2: True
BACKBONE: "FC-Densenet"
