TAG: "udnet"
PREFIX: "default"
PRED_TAG: "udnet"
IMG:
  BIT: 16
  W_WIDTH: 250
  W_LEVEL: 55
DATA:
  TRAINSET: "Liver_2016_train+Liver_2017_train+Liver_2018_train"
  VALSET: "Liver_2018_val"
  TESTSET: "Liver_2017_test+Liver_2018_test"
  TESTSET_3D: "Liver_2017_test_3D+Liver_2018_test_3D"
TRAIN:
  BS: 2
  DISPLAY: 200
  KEEP_PROB: 1.0
  LR: 0.001
  LR_DECAY: 0.1
  LR_STEP: [200000]
  MAP: "prob"
  MAX_ITERS: 200000
  SNAPSHOT_ITERS: 5000
  UPDATE_OPS: True
VAL:
  NEED: True
  NUMBER: 1000
  STEPS: 5000
  MAP: "bin"
TEST:
  BS_2D: 2
  BS_3D: 1
  ITER: 200000
MODEL:
  ACTIVATION: "relu"
  BLOCKS: 4
  CROSS_ENTROPY: 1.0
  GROWTH_RATE: 16
  INIT_CHANNELS: 32
  NUM_LAYERS_PER_BLOCK: [4,6,8,12]
  THETA: 1.0
  THRESHOLD: 0.5
  WEIGHT_DECAY: 0.00001
  WEIGHT_INITIALIZER: "trunc_norm"
BACKBONE: "UDN"
UDN:
  GROWTH_RATE: 16
  INIT_CHANNELS: 48
  NUM_BLOCKS: 4
  NUM_LAYERS_PER_BLOCK: [4,6,8,12]
  THETA: 1.0
  USE_DROPOUT: False
